### ISSUE TITLE
CTD in Hooks::UpdateCombatControllerSettings 1.4.4.5

### ISSUE THREAD

**Issue by AndbGame** [Scrabx3/Acheron#2]
few examples (not very usable, because custom build)

[2024-02-20-15-21-07.log](https://github.com/Scrabx3/Acheron/files/14350128/2024-02-20-15-21-07.log)
[2024-02-19-02-57-35.log](https://github.com/Scrabx3/Acheron/files/14350144/2024-02-19-02-57-35.log)

after debugging by this - https://github.com/AndbGame/Acheron/blob/d70963a1fcfb78c36e530b8d433198662e60d2d6/src/Acheron/Hooks/Hooks.cpp#L146

I am found few moments:
1. CTD occurs if `attackedActor` and/or `targetActor` is nullptr

2. have some race condition, which fixed by `group->lock.LockForWrite();`. but also looks fine if add this code to `SKSE::GetTaskInterface()->AddTask()`. Have suspection that `AddTask` is more reliable, but for now trying catch CTD with `LockForWrite` (CTD is pretty random - hard to catch)

**Comment by KrisV-777** [comment]
1. Are you sure its both? 
2. AddTask() would increase delay and thus likely just make it more unreliable than it already is (its more of a bandaid if the Detection Hook fails. Im still looking for a more reliable, permanent solution)

Id recommend in your test build to remove the continues in the second loop, if it crashes you can check which pointers were null prior to the crash - and that way you can be sure that it actually crashes because of these. If you find 2 instances where each one of them is null and it doesnt crash we can savely assume its only a mutex error (and if it does crash we know which of the 2 pointers arent allowed to be null)

**Comment by AndbGame** [comment]
> Are you sure its both?

I tested it without using `continue` - and yes, I am catch CTD if both `attackedActor`/`targetActor` is nullptr, or one of this (unfortunately, I don't remember which one, looks `targetActor` but not sure) (have suspection that it is related to Summons, which disapperar in mid battle - but I did not find any confirmation of this, it seemed that without Summons, the problem also arose)
Also I realize that tested it without `LockForWrite()` - make senses for repeat test again only  with `LockForWrite` (maybe it is enough)
(`LockForWrite` I added later, when found that 'nullptr guards' is not enough)

> AddTask() would increase delay and thus likely just make it more unreliable than it already is (its more of a bandaid if the Detection Hook fails. Im still looking for a more reliable, permanent solution)

yep. by this reason i trying catch CTD with `LockForWrite()` - but looks `LockForWrite` is fine... do not able reproduce any CTD for now

**Comment by AndbGame** [comment]
> Also I realize that tested it without LockForWrite() - make senses for repeat test again only with LockForWrite (maybe it is enough)

no, CTD and last logs
```
[13:27:39] [warning] Hooks::UpdateCombatControllerSettings attackedActor = nullptr
[13:27:39] [warning] Hooks::UpdateCombatControllerSettings targetActor = nullptr
```
(It is worth noting that it took a week to catch this case)

so return to solution with nullptr gurads + `LockForWrite()`

**Comment by AndbGame** [comment]
(and of course it seems to me that this problem should be solved in some other way, but I don't understand exactly how, i.e. in general, I think this is a workaround to avoid crashes)
